CC = gcc
CFLAGS = -Wall -fPIC
 
build: main
 
main: main.o so_stdio.o libso_stdio.so
	$(CC) $(CFLAGS) -o $@ $< -lhexdump_dynamic -L.

libso_stdio.so: so_stdio.o main.o
    $(CC) -shared -o $@ $^

so_stdio.o: so_stdio.c so_stdio.h
	$(CC) $(CFLAGS) so_stdio.c -c so_stdio.h -c

main.o: main.c
    $(CC) $(CFLAGS) main.c -c

.PHONY: clean
 
clean:
	rm -f *.o *~ main libso_stdio.so
